[project]
name = "medical-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.14"
dependencies = [
    "accelerate>=1.0.0",
    "huggingface-hub>=0.24.0",
    "langchain>=0.2.16",
    "langchain-community>=0.2.16",
    "langchain-huggingface>=1.2.0",
    "langchain-ollama>=1.0.1",
    "langchain-openai>=1.1.11",
    "langchain-tavily>=0.2.17",
    "matplotlib>=3.10.8",
    "mlflow>=3.9.0",
    "numpy>=1.26.0",
    "pandas>=2.2.0",
    "pillow>=12.1.0",
    "pinecone>=5.0.0",
    "pydantic>=2.7.0",
    "pymupdf>=1.24.0",
    "pytesseract>=0.3.13",
    "pytest>=9.0.2",
    "python-dotenv>=1.0.1",
    "rank-bm25>=0.2.2",
    "safetensors>=0.4.5",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "sentence-transformers==3.3.1",
    "tokenizers>=0.21.0,<0.22.0",
    "torch>=2.2.0",
    "torchaudio>=2.2.0",
    "torchvision>=0.17.0",
    "tqdm>=4.66.0",
    "transformers==4.47.1",
    "xgboost>=3.2.0",
]
