server:
  port: 8080

spring:
  application:
    name: CoreBackend

  datasource:
    url: jdbc:postgresql://localhost:5432/medical_db
    username: medical_user
    password: medical_password
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  storage:
    image-dir: "../data/resource_db/images"
    document-dir: "../data/resource_db/documents"